version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rake app:update:bin && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/project
    ports:
      - "3000:3000"
    depends_on:
      - db
